### PR TITLE
use authenticated fetch in human pane

### LINKED ISSUE #347: Display PDF-Files even if they can only be accessed authenticated
Currently on CSS if a PDF is not publically available SolidOS renders itself (instead of the pdf) in an iframe and shows an error:

image

### PR DESCRIPTION
**Pull request by bourgeoa**

### CODE REVIEW

File: src/humanReadablePane.js [hunk 1]
```diff
@@ -104,11 +101,20 @@ const humanReadablePane = {
...
+          const objectURL = URL.createObjectURL(myBlob)
+          frame.setAttribute('src', objectURL) // w640 h480 //
+          frame.setAttribute('class', 'doc')
+          frame.setAttribute('style', `border: 1px solid; padding: 1em; height:120em; width:80em; resize: both; overflow: auto;`)
+        })
     }
-
     // @@ Note below - if we set ANY sandbox, then Chrome and Safari won't display it if it is PDF.
     // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
     // You can;'t have any sandbox and allow plugins.
```
Comment (TallTed) [inline src/humanReadablePane.js]:
```suggestion
    // You can't have any sandbox and allow plugins.
```

File: src/humanReadablePane.js [hunk 2]
```diff
@@ -104,14 +101,23 @@ const humanReadablePane = {
     if (ct === 'text/markdown') {
       markdownHtml()
     } else {
-      frame.setAttribute('src', subject.uri) // allow-same-origin
-      frame.setAttribute('class', 'doc')
-      frame.setAttribute('style', 'resize = both; height:120em; width:80em;')
+      // get with authenticated fetch
+      console.log(`humanReadablePane: ${ct}`)
+      kb.fetcher._fetch(subject.uri)
```
Comment (angelo-v) [inline src/humanReadablePane.js:106]: **question** why not `kb.fetcher.webOperation` like with markdown?

Comment (bourgeoa) [reply src/humanReadablePane.js:106]: because kb.fetcher.webOperation either return resolve(response.text or resolve(response) so the reponse is already resolved

**Review by timea-solid — APPROVED** [review]
Tested locally on NSS and works.
